//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.05 at 03:22:47 AM EDT 
//


package com.panthers.panthers_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.panthers.panthers_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.panthers.panthers_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCharacterByIdResponse }
     * 
     */
    public GetCharacterByIdResponse createGetCharacterByIdResponse() {
        return new GetCharacterByIdResponse();
    }

    /**
     * Create an instance of {@link CharacterInfo }
     * 
     */
    public CharacterInfo createCharacterInfo() {
        return new CharacterInfo();
    }

    /**
     * Create an instance of {@link AddCharacterResponse }
     * 
     */
    public AddCharacterResponse createAddCharacterResponse() {
        return new AddCharacterResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetAllCharactersResponse }
     * 
     */
    public GetAllCharactersResponse createGetAllCharactersResponse() {
        return new GetAllCharactersResponse();
    }

    /**
     * Create an instance of {@link GetCharacterByIdRequest }
     * 
     */
    public GetCharacterByIdRequest createGetCharacterByIdRequest() {
        return new GetCharacterByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateCharacterRequest }
     * 
     */
    public UpdateCharacterRequest createUpdateCharacterRequest() {
        return new UpdateCharacterRequest();
    }

    /**
     * Create an instance of {@link AddCharacterRequest }
     * 
     */
    public AddCharacterRequest createAddCharacterRequest() {
        return new AddCharacterRequest();
    }

    /**
     * Create an instance of {@link DeleteCharacterRequest }
     * 
     */
    public DeleteCharacterRequest createDeleteCharacterRequest() {
        return new DeleteCharacterRequest();
    }

    /**
     * Create an instance of {@link UpdateCharacterResponse }
     * 
     */
    public UpdateCharacterResponse createUpdateCharacterResponse() {
        return new UpdateCharacterResponse();
    }

    /**
     * Create an instance of {@link DeleteCharacterResponse }
     * 
     */
    public DeleteCharacterResponse createDeleteCharacterResponse() {
        return new DeleteCharacterResponse();
    }

    /**
     * Create an instance of {@link GetAllCharactersRequest }
     * 
     */
    public GetAllCharactersRequest createGetAllCharactersRequest() {
        return new GetAllCharactersRequest();
    }

}
